create table word_lists (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table word_lists enable row level security;
create policy "Manage own lists" on word_lists for all using (auth.uid() = user_id);

create table word_list_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  word_list_id bigint references word_lists(id) on delete cascade not null,
  word text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table word_list_entries enable row level security;
create policy "Manage own word lists" on word_list_entries for all using (auth.uid() = user_id);

create table quizzes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  article_url text,
  article_title text,
  status text default 'in_progress', -- 'in_progress', 'finished'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table quizzes enable row level security;
create policy "Manage own quizzes" on quizzes for all using (auth.uid() = user_id);


create table quiz_word_lists (
  quiz_id bigint references quizzes(id) on delete cascade,
  word_list_id bigint references word_lists(id) on delete cascade,
  primary key (quiz_id, word_list_id)
);
-- No RLS needed on join table if policies on parents are sufficient, but enabling is good practice.
alter table quiz_word_lists enable row level security;
create policy "Manage own quiz lists" on quiz_word_lists for all using (
  exists (select 1 from quizzes where id = quiz_word_lists.quiz_id and user_id = auth.uid())
);

create table quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint references quizzes(id) on delete cascade not null,
  question text not null,
  word text not null,
  english text,
  question_order int
);
alter table quiz_questions enable row level security;
-- Questions are accessible if the user owns the quiz.
create policy "Manage own quiz questions" on quiz_questions for all using (
  exists (select 1 from quizzes where id = quiz_questions.quiz_id and user_id = auth.uid())
);

create table quiz_sessions (
  id bigint generated by default as identity primary key,
  quiz_id bigint references quizzes(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  score float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table quiz_sessions enable row level security;
create policy "Manage own sessions" on quiz_sessions for all using (auth.uid() = user_id);

create table quiz_attempts (
  id bigint generated by default as identity primary key,
  question_id bigint references quiz_questions(id) on delete cascade not null,
  session_id bigint references quiz_sessions(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  attempt text,
  is_correct boolean,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(question_id, session_id)
);
alter table quiz_attempts enable row level security;
create policy "Manage own attempts" on quiz_attempts for all using (auth.uid() = user_id);
